config/routes.rb
Rails.application.routes.draw do

  root "locations#new"

  resource :session, :only => [:create]
  get '/login' => 'sessions#new'
  delete '/logout' => 'sessions#destroy'

  resources :parking_violations, only: [:create]
  resources :locations, only: [:new, :create, :update, :show]
  resources :users, except: [:index, :destroy]
  resources :activities, only: [:index, :create]
  resources :comments, only: [:create]

end

app/views/shared/_comment.html.erb
<div class="comment">
  <%= comment.post_time %><br>
  <%= comment.body %> - <%= comment.author.username %><br>
</div>

app/views/shared/_comment_form.html.erb
<!--Comment Form-->

<%= form_for comment do |f| %>
  <%= f.text_area :body, rows: "2", placeholder: "Write a comment..." %>
  <%= f.hidden_field :commentable_id, value: commentable.id %>
  <%= f.hidden_field :commentable_type, value: commentable.class.name %>
  <%= f.submit "Comment" %>
<% end %>

app/views/shared/_flash.html.erb
<!--Flash Messages-->

<div class="flash-messages">

  <strong>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, :class => "") %>
    <% end %>
  </strong>

</div>

app/views/shared/_navbar.html.erb
<% if signed_in_user? %>
  <%= link_to "Logout", logout_path, :method => :delete %>
  <%= link_to current_user.username, user_path(current_user) %>
<% else %>
  <%= link_to "Login", login_path %>
  <%= link_to "Sign Up", new_user_path %>
<% end %>

<br>

<%= link_to "Check Your Location", new_location_path %>
<%= link_to "Activity Feed", activities_path %>

app/views/shared/flash.html.erb
<!--Flash Messages-->

<div class="flash-messages">

  <strong>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, :class => "") %>
    <% end %>
  </strong>

</div>